#!/bin/sh

# mds — A micro-display server
# Copyright © 2014, 2015  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

cd "$(dirname "$0")"

# Because bin/mds has setuid on all used libraries need to be in a path
# that is trusted by the dynamic linker. If it still says that the file
# is not found, add /usr/local/lib to /etc/ld.so.conf.
if [ ! -e bin/libmdsserver.so ]; then
    make DEBUG=y
fi
if [ ! -e /usr/local/lib/libmdsserver.so ]; then
    sudo cp bin/libmdsserver.so /usr/local/lib/libmdsserver.so
elif [ ! "$(cat /usr/local/lib/libmdsserver.so | sha256sum)" = "$(cat bin/libmdsserver.so | sha256sum)" ]; then
    sudo cp bin/libmdsserver.so /usr/local/lib/libmdsserver.so
fi

export OLD_XDG_CONFIG_HOME="${XDG_CONFIG_HOME}"
export PATH="$(pwd)/test.d:${PATH}"
export XDG_CONFIG_HOME="$(pwd)/test.d"

bin/mds

