#!/bin/sh

data="$(sed 's/\(.\) /\1\1/g' | sed 's/\./ /g' | sed 's/@/X/g' | sed 's/ \+$//g')"

while [ $(echo "${data}" | grep -v '^ ' | grep -v '^$' | wc -l) = 0 ]; do
    data="$(echo "${data}" | sed 's/^ //')"
done

echo "${data}"

