#!/bin/sh

# mds — A micro-display server
# Copyright © 2014, 2015, 2016  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


echo mds-server pid: $$
if [ -z "${NO_VALGRIND}" ]; then
    exec valgrind --leak-check=full --show-leak-kinds=all "$0".real "$@"
else
    exec "$0".real "$@"
fi

