#!/bin/bash

# mds — A micro-display server
# Copyright © 2014, 2015, 2016, 2017  Mattias Andrée (maandree@kth.se)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


echo "Successfully spawned mdsinitrc."

export PATH="$(realpath bin):${PATH}"
cd test.d
export XDG_CONFIG_HOME="${OLD_XDG_CONFIG_HOME}"
unset OLD_XDG_CONFIG_HOME
if [ -z "${XDG_CONFIG_HOME}" ]; then
    unset XDG_CONFIG_HOME
fi
g=
if [ -z "${NO_VALGRIND}" ]; then
    g="valgrind --leak-check=full --show-leak-kinds=all"
fi
if [ -z "${MDS_TEST}" ]; then
    $g mds-respawn --interval=10 \
	{ sleep 4s } \
	{ sleep 1m } \
	{ $g mds-echo } \
	&
    if which terminator 2>/dev/null >&2; then
        exec terminator
    else
        exec xterm
    fi
elif [ "${MDS_TEST}" = kkbd ]; then
    exec $g mds-kkbd
else
    echo 'Bad value of ${MDS_TEST}'
fi

